version: '3'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    hostname: postgres
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounts-db
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my-network

volumes:
  postgresql_data:
    driver: local

networks:
  my-network:
    driver: bridge