version: '3'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    hostname: postgres
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounts-db
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my-network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus/
    networks:
      - my-network
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - my-network

volumes:
  postgresql_data:
    driver: local
  grafana_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  my-network:
    driver: bridge