spring:
  name: account-management-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_PATH:jdbc:postgresql://localhost:5555/accounts-db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: 'health,prometheus'
  endpoint:
    health:
      show-details: always
account-management:
  validation:
    sources: ${SOURCES:mail=firstName,email;mobile=phoneNumber;bank=bankId,lastName,firstName,middleName,birthDate,passportNumber;gosuslugi=bankId,lastName,firstName,middleName,birthDate,birthPlace,passportNumber,phoneNumber,registrationAddress}