spring:
  name: account-management-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_PATH:jdbc:postgresql://localhost:5432/accounts-db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
springdoc:
  swagger-ui:
    path: swagger-ui.html
account-management:
  validation:
    sources: ${SOURCES:mail=firstName,email;mobile=phoneNumber;bank=bankId,lastName,firstName,middleName,birthDate,passportNumber;gosuslugi=bankId,lastName,firstName,middleName,birthDate,birthPlace,passportNumber,phoneNumber,registrationAddress}